### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by luxas** [resin-io-projects/armv7hf-debian-qemu#1]
Hello @petrosagg and thanks again for this contribution!

I'm planning to include this in the Kubernetes ARM images, are you OK with that?
I guess a licence must be present for not-self-written code, before it can be merged into k8s mainline

So what kind of license has this project? MIT?

**Comment by luxas** [comment]
And BTW, have you merged your patch into `qemu` mainline?

**Comment by petrosagg** [comment]
Hey @luxas I added the LICENCE file. We use Apache 2.0 for all our projects in resin so I did the same here.

I haven't merged my patch into `qemu` mainline yet, I'll do some cleanup and send it next week.

**Comment by petrosagg** [comment]
And yeah, no problem using that in your Kubernetes for ARM project :)
