### ISSUE TITLE
Extremely slow

### ISSUE THREAD

**Issue by wouterds** [resin-io-projects/armv7hf-debian-qemu#10]
Compiling simple packages takes literally hours while on my Macbook for example it takes a few minutes. Isn't there a way to make qemu use the full potential & resources of the host?

I don't know anything about it really, so it's more of a question if this is possible.

**Comment by JSurf** [comment]
qemu completely emulates a different architecture so you can run arm binaries on a x86_64 machine. This comes with the price of slow performance. If you need full performance stick to the architecture of your host system

**Comment by petrosagg** [comment]
@wouterds as @JSurf said the fact that QEMU emulates a CPU makes it pretty slow. The only way to compile something for ARM at the same speed you compile x86 binaries is to use a cross compiler toolchain.
