### ISSUE TITLE
Executing commands

### ISSUE THREAD

**Issue by jgato** [resin-io-projects/armv7hf-debian-qemu#6]
Hi there,

I have managed to build a docker image for ARM in an INTEL machine thanks to your image. But, what if I want to execute commands? How I have to put the entrypoints or commands to be under the qemu "trick"?

**Comment by ibrahima** [comment]
Last time I got it this image to work, I could just run `docker run -it resin/armv7hf-debian-qemu bash` and then I could run any ARM binaries inside the image (in fact, the userspace seemed to all be ARM). But now I can't get the image to work anymore...

**Comment by tsuckow** [comment]
It doesn't look like sh is getting copied to sh.real anymore

**Comment by ibrahima** [comment]
I think you're right, looking at https://github.com/resin-io-projects/armv7hf-debian-qemu/blob/master/resin-xbuild.go it doesn't seem like cross-build-start has anything that copies /bin/sh to /bin/sh.real. Unfortunatately I don't know how to build the go binary or I'd test it out myself, but it seems like that's all that's missing. Good find!

**Comment by show0k** [comment]
~~I tried [this fix](https://github.com/show0k/armv7hf-debian-qemu/commit/acc3f14b447c2403236bee5464120ecc9b6d0b14), but it doesn't work better. you can test on [docker hub show0k/armv7hf-debian-qemu](https://hub.docker.com/r/show0k/armv7hf-debian-qemu/)~~
~~Any image based on armv7hf-debian-qemu manage to be built on x64, but to run it:~~
- ~~on OSX with "docker for Mac", it uses all my docker ressources without doing anything~~
- ~~on x64 Linux I manage to run with the real qemu `docker run -it -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static resin/armv7hf-debian-qemu bash`~~
- ~~on ARMv7 Linux it run well~~

I manage to make it work too on [show0k/miniconda-armv7](https://github.com/show0k/docker-miniconda-armv7).

**Comment by tsuckow** [comment]
I got it working on [tsuckow/rpi-raspbian-qemu](https://github.com/tsuckow/rpi-raspbian-qemu) by tweaking the setup line. I also added comments on how to use it

**Comment by show0k** [comment]
Ok, so the trick is only to specify the entrypoint

```
 docker run -it --entrypoint=/usr/bin/qemu-arm-static resin/armv7hf-debian-qemu /bin/bash
```

You can specify the entrypoint on the Dockerfile directly but the image won't work on ARM I suppose.

**Comment by jgato** [comment]
@show0k I am trying your solution, and now I can run a bash container over an image that I have created using resin/armv7hf-debian-qemu as base. So, bash is ok.

But this image is a nodejs project, so I am trying to do something like:

```
docker run -it --entrypoint=/usr/bin/qemu-arm-static foo/bar npm test
```

What I have in response is 

```
Error while loading npm: No such file or directory
```

I can invoke bash, and inside the container I can do npm test without problems.

**Comment by show0k** [comment]
@jgato The PATH is a bit messy, try with the full URI of the binary, something like /bin/npm depending on your install.

**Comment by jgato** [comment]
@show0k now I can find the npm command but I have an exec format error :(

```
$> docker run -it --entrypoint=/usr/bin/qemu-arm-static foo/bar /usr/bin/npm test
Error while loading /usr/bin/npm: Exec format error

```

**Comment by tsuckow** [comment]
Npm probably doesn't fork, so it may not be an issue here but be wary of zombies.

I have no idea if qemu will properly reap orphaned processes. Normally the shell would manage that.

**Comment by tsuckow** [comment]
OK, it probably does fork. You likely need to run /bin/env and set the execve variable that's in this dockerfile and then invoke qemu again and then npm

Edit: or im a dipshit and there is probably a way to set it with the docker run command

**Comment by jgato** [comment]
Sorry, I fear I dont understand your steps :(

**Comment by tsuckow** [comment]
From memory on my phone:

```
docker run -it --entrypoint=/usr/bin/qemu-arm-static resin/armv7hf-debian-qemu /bin/env QEMU_EXECVE=1 /usr/bin/qemu-arm-static /usr/bin/nodejs
```

**Comment by jgato** [comment]
it does not work:

```
$> docker run -it --entrypoint=/usr/bin/qemu-arm-static foo/bar /usr/bin/env QEMU_EXECVE=1 /usr/bin/qemu-arm-static /usr/bin/nodejs
/usr/bin/qemu-arm-static: Invalid ELF image for this architecture

```

In my CI integration workflow I have managed to build the docker image for ARM in an Intel machine. Now I want to use this same machine to execute a test process.

**Comment by jgato** [comment]
Ok I got it!!, thanks @tsuckow  I have slightly modified your command, it was extrange to me this invocation of qemu-arm-static twice. Now it works in that way:

```
$> docker run -it --entrypoint=/usr/bin/qemu-arm-static foo/bar /usr/bin/env QEMU_EXECVE=1  /usr/bin/npm test
All test passed ;) 

```

thanks!!

**Comment by petrosagg** [comment]
@jgato you can also pass this environment variable like so: `docker run -it --entrypoint=/usr/bin/qemu-arm-static -e QEMU_EXECVE=1 foo/bar /usr/bin/npm test` but if you include `ENV QEMU_EXECVE 1` in the dockerfile that produced `foo/bar` or if `foo/bar` is a descendant of `resin/armv7hf-debian-qemu` then it should work without it.

On my machine the following works and I can also spawn child processes fine:

`docker run -it --entrypoint=qemu-arm-static resin/armv7hf-debian-qemu /bin/bash`

I'm on docker 1.12

**Comment by petrosagg** [comment]
@ibrahima I added a `build.sh` script that shows how to build `resin-xbuild.go`

**Comment by jgato** [comment]
@petrosagg but if I set this env variable in the dockerfile, what will happen if I try to run containers over the image in a real ARM machine? it will go through the qemu?

**Comment by petrosagg** [comment]
@jgato if you run the image on real ARM hardware all you have to do is omit the `--entrypoint=qemu-arm-static` parameter and QEMU won't be invoked. You'd still have the env var lingering in your scripts but it won't trigger anything

**Comment by jgato** [comment]
it seems to work for things like executing bash, but not for an npm test :(

**Comment by petrosagg** [comment]
Can you post a Dockerfile that starts with `FROM resin/armv7hf-debian-qemu` and steps to reproduce?

**Comment by jgato** [comment]
Sure....

```

FROM resin/armv7hf-debian-qemu

# "trick" from resin to build arm images using qemu
# https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

RUN [ "cross-build-start" ]

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# installing the stuff
RUN apt-get update && apt-get install -y \
    nodejs \
    npm \
    alsa-utils \
    libasound2-dev \
    festival \
    festvox-kallpc16k \
    pulseaudio

COPY package.json /usr/src/app/
RUN npm config set strict-ssl false
RUN npm install

RUN ln -s /usr/bin/nodejs /usr/bin/node

# Bundle app source
COPY . /usr/src/app
RUN echo '{}' > /usr/src/app/config.json
ENV QEMU_EXECVE 1

RUN [ "cross-build-end" ]
```

**Comment by petrosagg** [comment]
Can you also send your package.json? My suspicion is that some process along the way clears the environment before an `execve()` and `QEMU_EXECVE` is lost.

**Comment by jgato** [comment]
Great

```
{
    "name": "ghost-core",
    "description": "Simple example saying names comming from an AEON's entity",
    "repository": {
        "type": "git",
        "url": "https://gitlab...../ghost-core"
    },

    "version": "0.1.8",
    "dependencies": {
        "aeonsdk-node": "https://gitlab......SDK/releases/nodejs/AeonSDK-nodejs_0.2.1.tgz",
        "say" : "^0.6.0",
        "moment-timezone": "*",
        "colog": "*",
        "node-rest-client": "*",
        "body-parser": "~1.12.4",
        "express": "~4.12.4"
    },
    "scripts": {
        "test": "node test"
    },
    "license": "Apache-2.0",
    "contributors": [{
        "name": "Jose Gato Luis",
        "email": "jose.gato@atos.net"
    }],
    "engines": {
        "node": "0.10.22"
    }
}

```

**Comment by JSurf** [comment]
First thanks for this technique, it is a really great  feature to be able to do automated arm builds on docker hub!

I'm using
https://hub.docker.com/r/multiarch/qemu-user-static/
to enable cross-platform support for arm containers on x64 for testing purposes.

After reading this thread im still trying to understand why this worked on an x64 machine in the first version (Commit: 96cc4cbfbce04cbcdcc3b201f7bd3106b18f42d8) , but does not work with the current HEAD:

 git clone https://github.com/resin-io-projects/armv7hf-debian-qemu.git 
 docker build -t debian-qemu .
 docker run --rm --privileged multiarch/qemu-user-static:register
 docker run -it --rm debian-qemu bash
-> This will not work, container just hangs after starting

But this will work:
 git clone https://github.com/resin-io-projects/armv7hf-debian-qemu.git 
 git checkout 96cc4cbfbce04cbcdcc3b201f7bd3106b18f42d8
 docker build -t debian-qemu .
 docker run --rm --privileged multiarch/qemu-user-static:register
 docker run -it --rm debian-qemu bash
-> This works, i get a command prompt and can run commands

This also works with any other ARM based image:
 docker run --rm --privileged multiarch/qemu-user-static:register
 docker run -it --rm resin/rpi-raspbian bash
-> works and shows the command prompt

Since cross-build is only intended to solve cross-platform issues while **building** the image i am not sure how this influences the produced image when **running** a container, i think the produced image should behave like any other ARM image

Somebody can clarify why the "entrypoint" workaround is needed with the latest version and it is not enough to just enable binfmt support via multiarch/qemu-user-static ?
