### ISSUE TITLE
Update qemu-arm-static?

### ISSUE THREAD

**Issue by alexgavrisco** [resin-io-projects/armv7hf-debian-qemu#9]
Hi,

I have an annoying bug related to qemu - it hangs while compiling something (in my case opencv) with cmake.
I found this ticket https://bugs.launchpad.net/qemu/+bug/955379

The fix is part of qemu 2.7. Is it possible to get updated binary for qemu-arm-static?

**Comment by kpayson64** [comment]
+1, I ran into the same issue

**Comment by alexgavrisco** [comment]
@kpayson64 Well, I've forked a repo and updated the binary.
https://github.com/Alexx-G/docker-rpi-raspbian

I've experienced arbitrary lags, but I've managed to compile what I needed.

**Comment by petrosagg** [comment]
@Alexx-G @kpayson64 QEMU updated to 2.9.0. I've pushed the new image to Dockerhub
